# Generated by Django 5.2.8 on 2026-01-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
