# Generated by Django 5.2.8 on 2026-01-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_dish_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
