# Generated by Django 5.2.8 on 2026-01-03 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_alter_dish_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
