# Generated by Django 5.2.8 on 2026-01-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_alter_reservation_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="comment",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
