# Generated by Django 5.2.8 on 2026-01-04 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_alter_reservation_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="reservation_date",
            new_name="reserved_at",
        ),
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
